{
    "Modified": "2014-11-17T12:03:58.933000",
    "Published": "2014-11-15T20:59:01.927000",
    "access": {
        "authentication": "NONE",
        "complexity": "MEDIUM",
        "vector": "LOCAL"
    },
    "capec": [
        {
            "id": "26",
            "name": "Leveraging Race Conditions",
            "prerequisites": "A resource is accessed/modified concurrently by multiple processes such that a race condition exists.\nThe attacker has the ability to modify the resource.",
            "related_weakness": [
                "368",
                "363",
                "366",
                "370",
                "362",
                "662",
                "689",
                "667",
                "665"
            ],
            "solutions": "Use safe libraries to access resources such as files.\nBe aware that improper use of access function calls such as chown(), tempfile(), chmod(), etc. can cause a race condition.\nUse synchronization to control the flow of execution.\nUse static analysis tools to find race conditions.\nPay attention to concurrency problems related to the access of resources.",
            "summary": "This attack targets a race condition occurring when multiple processes access and manipulate the same resource concurrently and the outcome of the execution depends on the particular order in which the access takes place. The attacker can leverage a race condition by \"running the race\", modifying the resource and modifying the normal execution flow. For instance a race condition can occur while accessing a file, the attacker can trick the system by replacing the original file with his version and cause the system to read the malicious file."
        },
        {
            "id": "29",
            "name": "Leveraging Time-of-Check and Time-of-Use (TOCTOU) Race Conditions",
            "prerequisites": "A resource is access/modified concurrently by multiple processes.\nThe attacker is able to modify resource.\nA race condition exists while accessing a resource.",
            "related_weakness": [
                "367",
                "368",
                "366",
                "370",
                "362",
                "662",
                "691",
                "663",
                "665"
            ],
            "solutions": "Use safe libraries to access resources such as files.\nBe aware that improper use of access function calls such as chown(), tempfile(), chmod(), etc. can cause a race condition.\nUse synchronization to control the flow of execution.\nUse static analysis tools to find race conditions.\nPay attention to concurrency problems related to the access of resources.",
            "summary": "This attack targets a race condition occurring between the time of check (state) for a resource and the time of use of a resource. The typical example is the file access. The attacker can leverage a file access race condition by \"running the race\", meaning that he would modify the resource between the first time the target program accesses the file and the time the target program uses the file. During that period of time, the attacker could do something such as replace the file and cause an escalation of privilege."
        }
    ],
    "cvss": "3.3",
    "cvss-time": "2014-11-17T12:03:58.543000",
    "cwe": "CWE-362",
    "id": "CVE-2014-2667",
    "impact": {
        "availability": "NONE",
        "confidentiality": "PARTIAL",
        "integrity": "PARTIAL"
    },
    "last-modified": "2017-06-30T21:29:05.810000",
    "nessus": [
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "OPENSUSE-2014-334.NASL",
            "description": "This python update fixes the following security issue :\n\n  - bnc#871152: Fixed race condition with umask when     creating directories with os.mkdirs (CVE-2014-2667).",
            "last seen": "2019-02-21",
            "modified": "2018-11-10",
            "plugin id": "75344",
            "published": "2014-06-13",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=75344",
            "title": "openSUSE Security Update : python3 (openSUSE-SU-2014:0596-1)"
        },
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "OPENSUSE-2014-333.NASL",
            "description": "This python update fixes the following security and non-security issues :\n\n  - bnc#869222: Fixed DoS when opening malicious archives     (CVE-2013-7338).\n\n  - bnc#863741: Fixed buffer overflow in     socket.recvfrom_into (CVE-2014-1912).\n\n  - bnc#871152: Fixed race condition with umask when     creating directories with os.mkdirs (CVE-2014-2667).\n\n  - bnc#637176: Fixed update multilib patch to handle home     install scheme.",
            "last seen": "2019-02-21",
            "modified": "2018-11-10",
            "plugin id": "75343",
            "published": "2014-06-13",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=75343",
            "title": "openSUSE Security Update : python3 (openSUSE-SU-2014:0597-1)"
        },
        {
            "NASL family": "Fedora Local Security Checks",
            "NASL id": "FEDORA_2014-16393.NASL",
            "description": "Fixes CVEs 2013-7338 and 2014-2667.\n\nNote that Tenable Network Security has extracted the preceding description block directly from the Fedora security advisory. Tenable has attempted to automatically clean and format it as much as possible without introducing additional issues.",
            "last seen": "2019-02-21",
            "modified": "2018-12-05",
            "plugin id": "79940",
            "published": "2014-12-15",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=79940",
            "title": "Fedora 20 : python3-3.3.2-19.fc20 (2014-16393)"
        },
        {
            "NASL family": "Fedora Local Security Checks",
            "NASL id": "FEDORA_2014-16479.NASL",
            "description": "Fixes CVEs 2013-7338 and 2014-2667.\n\nNote that Tenable Network Security has extracted the preceding description block directly from the Fedora security advisory. Tenable has attempted to automatically clean and format it as much as possible without introducing additional issues.",
            "last seen": "2019-02-21",
            "modified": "2018-12-05",
            "plugin id": "80368",
            "published": "2015-01-06",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=80368",
            "title": "Fedora 19 : python3-3.3.2-11.fc19 (2014-16479)"
        },
        {
            "NASL family": "Mandriva Local Security Checks",
            "NASL id": "MANDRIVA_MDVSA-2015-076.NASL",
            "description": "Updated python3 packages fix security vulnerabilities :\n\nZipExtFile.read goes into 100% CPU infinite loop on maliciously binary edited zips (CVE-2013-7338).\n\nA vulnerability was reported in Python's socket module, due to a boundary error within the sock_recvfrom_into() function, which could be exploited to cause a buffer overflow. This could be used to crash a Python application that uses the socket.recvfrom_info() function or, possibly, execute arbitrary code with the permissions of the user running vulnerable Python code (CVE-2014-1912).\n\nIt was reported that a patch added to Python 3.2 caused a race condition where a file created could be created with world read/write permissions instead of the permissions dictated by the original umask of the process. This could allow a local attacker that could win the race to view and edit files created by a program using this call. Note that prior versions of Python, including 2.x, do not include the vulnerable _get_masked_mode() function that is used by os.makedirs() when exist_ok is set to True (CVE-2014-2667).\n\nPython are susceptible to arbitrary process memory reading by a user or adversary due to a bug in the _json module caused by insufficient bounds checking. The bug is caused by allowing the user to supply a negative value that is used an an array index, causing the scanstring function to access process memory outside of the string it is intended to access (CVE-2014-4616).\n\nThe CGIHTTPServer Python module does not properly handle URL-encoded path separators in URLs. This may enable attackers to disclose a CGI script's source code or execute arbitrary scripts in the server's document root (CVE-2014-4650).",
            "last seen": "2019-02-21",
            "modified": "2018-08-03",
            "plugin id": "82329",
            "published": "2015-03-30",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=82329",
            "title": "Mandriva Linux Security Advisory : python3 (MDVSA-2015:076)"
        },
        {
            "NASL family": "Gentoo Local Security Checks",
            "NASL id": "GENTOO_GLSA-201503-10.NASL",
            "description": "The remote host is affected by the vulnerability described in GLSA-201503-10 (Python: Multiple vulnerabilities)\n\n    Multiple vulnerabilities have been discovered in Python. Please review       the CVE identifiers referenced below for details.\n  Impact :\n\n    A context-dependent attacker may be able to execute arbitrary code or       cause a Denial of Service condition.\n  Workaround :\n\n    There is no known workaround at this time.",
            "last seen": "2019-02-21",
            "modified": "2018-08-02",
            "plugin id": "82009",
            "published": "2015-03-24",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=82009",
            "title": "GLSA-201503-10 : Python: Multiple vulnerabilities"
        }
    ],
    "ranking": [
        [
            {
                "circl": 3
            }
        ]
    ],
    "references": [
        "http://bugs.python.org/issue21082",
        "http://lists.opensuse.org/opensuse-updates/2014-05/msg00007.html",
        "http://lists.opensuse.org/opensuse-updates/2014-05/msg00008.html",
        "http://www.openwall.com/lists/oss-security/2014/03/28/15",
        "http://www.openwall.com/lists/oss-security/2014/03/29/5",
        "http://www.openwall.com/lists/oss-security/2014/03/30/4",
        "https://security.gentoo.org/glsa/201503-10"
    ],
    "refmap": {
        "confirm": [
            "http://bugs.python.org/issue21082"
        ],
        "gentoo": [
            "GLSA-201503-10"
        ],
        "mlist": [
            "[oss-security] 20140328 CVE request: os.makedirs(exist_ok=True) is not thread-safe in Python",
            "[oss-security] 20140329 Re: [PSRT] CVE request: os.makedirs(exist_ok=True) is not thread-safe in Python",
            "[oss-security] 20140330 Re: CVE request: os.makedirs(exist_ok=True) is not thread-safe in Python"
        ],
        "suse": [
            "openSUSE-SU-2014:0596",
            "openSUSE-SU-2014:0597"
        ]
    },
    "summary": "Race condition in the _get_masked_mode function in Lib/os.py in Python 3.2 through 3.5, when exist_ok is set to true and multiple threads are used, might allow local users to bypass intended file permissions by leveraging a separate application vulnerability before the umask has been set to the expected value.",
    "vulnerable_configuration": [
        {
            "id": "cpe:2.3:a:python:python:3.2.0",
            "title": "Python 3.2.0"
        },
        {
            "id": "cpe:2.3:a:python:python:3.2.1",
            "title": "Python 3.2.1"
        },
        {
            "id": "cpe:2.3:a:python:python:3.2.2",
            "title": "Python 3.2.2"
        },
        {
            "id": "cpe:2.3:a:python:python:3.2.3",
            "title": "Python 3.2.3"
        },
        {
            "id": "cpe:2.3:a:python:python:3.2.4",
            "title": "Python 3.2.4"
        },
        {
            "id": "cpe:2.3:a:python:python:3.2.5",
            "title": "Python 3.2.5"
        },
        {
            "id": "cpe:2.3:a:python:python:3.2.6",
            "title": "Python 3.2.6"
        },
        {
            "id": "cpe:2.3:a:python:python:3.3.0",
            "title": "Python 3.3.0"
        },
        {
            "id": "cpe:2.3:a:python:python:3.3.1",
            "title": "Python 3.3.1"
        },
        {
            "id": "cpe:2.3:a:python:python:3.3.2",
            "title": "Python 3.3.2"
        },
        {
            "id": "cpe:2.3:a:python:python:3.3.3",
            "title": "Python 3.3.3"
        },
        {
            "id": "cpe:2.3:a:python:python:3.3.4",
            "title": "Python 3.3.4"
        },
        {
            "id": "cpe:2.3:a:python:python:3.3.5",
            "title": "Python 3.3.5"
        },
        {
            "id": "cpe:2.3:a:python:python:3.3.6",
            "title": "Python 3.3.6"
        },
        {
            "id": "cpe:2.3:a:python:python:3.4.0",
            "title": "Python 3.4.0"
        },
        {
            "id": "cpe:2.3:a:python:python:3.4.1",
            "title": "Python 3.4.1"
        },
        {
            "id": "cpe:2.3:a:python:python:3.4.2",
            "title": "Python 3.4.2"
        }
    ],
    "vulnerable_configuration_cpe_2_2": [
        "cpe:/a:python:python:3.2.0",
        "cpe:/a:python:python:3.2.1",
        "cpe:/a:python:python:3.2.2",
        "cpe:/a:python:python:3.2.3",
        "cpe:/a:python:python:3.2.4",
        "cpe:/a:python:python:3.2.5",
        "cpe:/a:python:python:3.2.6",
        "cpe:/a:python:python:3.3.0",
        "cpe:/a:python:python:3.3.1",
        "cpe:/a:python:python:3.3.2",
        "cpe:/a:python:python:3.3.3",
        "cpe:/a:python:python:3.3.4",
        "cpe:/a:python:python:3.3.5",
        "cpe:/a:python:python:3.3.6",
        "cpe:/a:python:python:3.4.0",
        "cpe:/a:python:python:3.4.1",
        "cpe:/a:python:python:3.4.2"
    ]
}