{
    "Modified": "2012-10-30T23:06:35.357-04:00",
    "Published": "2008-11-10T11:15:12.140-05:00",
    "access": {
        "authentication": "NONE",
        "complexity": "LOW",
        "vector": "NETWORK"
    },
    "capec": [],
    "cvss": 10.0,
    "cvss-time": "2008-11-11T11:36:00.000-05:00",
    "cwe": "CWE-189",
    "id": "CVE-2008-5031",
    "impact": {
        "availability": "COMPLETE",
        "confidentiality": "COMPLETE",
        "integrity": "COMPLETE"
    },
    "map_cve_gentoo": {
        "gentooid": "GLSA-200907-16"
    },
    "map_cve_nessus": {
        "nessus_script_family": "Red Hat Local Security Checks",
        "nessus_script_file": "redhat-RHSA-2009-1176.nasl",
        "nessus_script_id": "40400",
        "nessus_script_name": "RHEL 5 : python (RHSA-2009:1176)"
    },
    "map_cve_openvas": {
        "openvas_script_family": "CentOS Local Security Checks",
        "openvas_script_file": "ovcesa2009_1176.nasl",
        "openvas_script_id": "64583",
        "openvas_script_name": "CentOS Security Advisory CESA-2009:1176 (python)"
    },
    "map_cve_oval": {
        "cpeid": "",
        "ovalclass": "vulnerability",
        "ovalid": "oval:org.mitre.oval:def:8564",
        "ovaltitle": "VMware python multiple integer overflows vulnerability"
    },
    "map_cve_redhat": {
        "redhatid": "RHSA-2009:1178",
        "redhatovalid": "oval:com.redhat.rhsa:def:20091178",
        "redhatupdatedesc": "RHSA-2009:1178: python security update (Moderate)"
    },
    "map_cve_scip": {
        "scipid": "44964",
        "sciplink": "http://www.scip.ch/en/?vuldb.44964"
    },
    "map_cve_vmware": {
        "vmwareid": "VMSA-2009-0016"
    },
    "map_redhat_bugzilla": {
        "advisory_dateissue": "2009-07-27",
        "bugzillaid": "470915",
        "bugzillatitle": "CVE-2008-5031 python: stringobject, unicodeobject integer overflows",
        "redhatid": "RHSA-2009:1178"
    },
    "ranking": [
        [
            {
                "circl": 2
            }
        ]
    ],
    "references": [
        "http://xforce.iss.net/xforce/xfdb/46612",
        "http://www.vupen.com/english/advisories/2009/3316",
        "http://www.vmware.com/security/advisories/VMSA-2009-0016.html",
        "http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded",
        "http://www.openwall.com/lists/oss-security/2008/11/05/3",
        "http://www.openwall.com/lists/oss-security/2008/11/05/2",
        "http://svn.python.org/view?rev=61350&view=rev",
        "http://svn.python.org/view/python/trunk/Objects/unicodeobject.c?rev=61350&view=diff&r1=61350&r2=61349&p1=python/trunk/Objects/unicodeobject.c&p2=/python/trunk/Objects/unicodeobject.c",
        "http://svn.python.org/view/python/trunk/Objects/stringobject.c?rev=61350&view=diff&r1=61350&r2=61349&p1=python/trunk/Objects/stringobject.c&p2=/python/trunk/Objects/stringobject.c",
        "http://support.apple.com/kb/HT3438",
        "http://security.gentoo.org/glsa/glsa-200907-16.xml",
        "http://scary.beasts.org/security/CESA-2008-008.html",
        "http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html"
    ],
    "summary": "Multiple integer overflows in Python 2.2.3 through 2.5.1, and 2.6, allow context-dependent attackers to have an unknown impact via a large integer value in the tabsize argument to the expandtabs method, as implemented by (1) the string_expandtabs function in Objects/stringobject.c and (2) the unicode_expandtabs function in Objects/unicodeobject.c.  NOTE: this vulnerability reportedly exists because of an incomplete fix for CVE-2008-2315.",
    "vulnerable_configuration": [
        {
            "id": "cpe:2.3:a:python:python:2.2.3",
            "title": "Python 2.2.3"
        },
        {
            "id": "cpe:2.3:a:python:python:2.3.7",
            "title": "Python 2.3.7"
        },
        {
            "id": "cpe:2.3:a:python:python:2.4.6",
            "title": "Python 2.4.6"
        },
        {
            "id": "cpe:2.3:a:python:python:2.5.1",
            "title": "Python 2.5.1"
        },
        {
            "id": "cpe:2.3:a:python:python:2.6",
            "title": "Python 2.6"
        }
    ],
    "vulnerable_configuration_cpe_2_2": [
        "cpe:/a:python:python:2.2.3",
        "cpe:/a:python:python:2.3.7",
        "cpe:/a:python:python:2.4.6",
        "cpe:/a:python:python:2.5.1",
        "cpe:/a:python:python:2.6"
    ]
}