{
    "Modified": "2017-09-29T01:30:00",
    "Published": "2008-04-22T04:41:00",
    "access": {
        "authentication": "NONE",
        "complexity": "MEDIUM",
        "vector": "NETWORK"
    },
    "assigner": "cve@mitre.org",
    "capec": [],
    "cvss": 6.8,
    "cvss-time": "2017-09-29T01:30:00",
    "cvss-vector": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
    "cwe": "CWE-189",
    "id": "CVE-2008-1679",
    "impact": {
        "availability": "PARTIAL",
        "confidentiality": "PARTIAL",
        "integrity": "PARTIAL"
    },
    "last-modified": "2017-09-29T01:30:00",
    "oval": [
        {
            "accepted": "2013-04-29T04:06:52.162-04:00",
            "class": "vulnerability",
            "contributors": [
                {
                    "name": "Aharon Chernin",
                    "organization": "SCAP.com, LLC"
                },
                {
                    "name": "Dragos Prisaca",
                    "organization": "G2, Inc."
                }
            ],
            "definition_extensions": [
                {
                    "comment": "The operating system installed on the system is Red Hat Enterprise Linux 3",
                    "oval": "oval:org.mitre.oval:def:11782"
                },
                {
                    "comment": "CentOS Linux 3.x",
                    "oval": "oval:org.mitre.oval:def:16651"
                },
                {
                    "comment": "The operating system installed on the system is Red Hat Enterprise Linux 4",
                    "oval": "oval:org.mitre.oval:def:11831"
                },
                {
                    "comment": "CentOS Linux 4.x",
                    "oval": "oval:org.mitre.oval:def:16636"
                },
                {
                    "comment": "Oracle Linux 4.x",
                    "oval": "oval:org.mitre.oval:def:15990"
                }
            ],
            "description": "Multiple integer overflows in imageop.c in Python before 2.5.3 allow context-dependent attackers to cause a denial of service (crash) and possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows.  NOTE: this issue is due to an incomplete fix for CVE-2007-4965.",
            "family": "unix",
            "id": "oval:org.mitre.oval:def:10583",
            "status": "accepted",
            "submitted": "2010-07-09T03:56:16-04:00",
            "title": "Multiple integer overflows in imageop.c in Python before 2.5.3 allow context-dependent attackers to cause a denial of service (crash) and possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows.  NOTE: this issue is due to an incomplete fix for CVE-2007-4965.",
            "version": "29"
        },
        {
            "accepted": "2010-03-01T04:00:13.347-05:00",
            "class": "vulnerability",
            "contributors": [
                {
                    "name": "Pai Peng",
                    "organization": "Hewlett-Packard"
                }
            ],
            "definition_extensions": [
                {
                    "comment": "Solaris 10 (SPARC) is installed",
                    "oval": "oval:org.mitre.oval:def:1440"
                },
                {
                    "comment": "Solaris 10 (x86) is installed",
                    "oval": "oval:org.mitre.oval:def:1926"
                }
            ],
            "description": "Multiple integer overflows in imageop.c in Python before 2.5.3 allow context-dependent attackers to cause a denial of service (crash) and possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows.  NOTE: this issue is due to an incomplete fix for CVE-2007-4965.",
            "family": "unix",
            "id": "oval:org.mitre.oval:def:7800",
            "status": "accepted",
            "submitted": "2010-01-19T17:52:34.000-05:00",
            "title": "Multiple Buffer and Integer Overflow Vulnerabilities in Python (python(1)) May Lead to a Denial of Service (DoS) or Allow Execution of Arbitrary Code",
            "version": "35"
        }
    ],
    "redhat": {
        "rpms": [
            "python-0:2.3.4-14.7.el4_8.2",
            "python-debuginfo-0:2.3.4-14.7.el4_8.2",
            "python-devel-0:2.3.4-14.7.el4_8.2",
            "python-docs-0:2.3.4-14.7.el4_8.2",
            "python-tools-0:2.3.4-14.7.el4_8.2",
            "tkinter-0:2.3.4-14.7.el4_8.2",
            "python-0:2.2.3-6.11",
            "python-debuginfo-0:2.2.3-6.11",
            "python-devel-0:2.2.3-6.11",
            "python-tools-0:2.2.3-6.11",
            "tkinter-0:2.2.3-6.11"
        ]
    },
    "references": [
        "http://bugs.python.org/issue1179",
        "http://bugs.python.org/msg64682",
        "http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html",
        "http://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html",
        "http://secunia.com/advisories/29889",
        "http://secunia.com/advisories/29955",
        "http://secunia.com/advisories/30872",
        "http://secunia.com/advisories/31255",
        "http://secunia.com/advisories/31358",
        "http://secunia.com/advisories/31365",
        "http://secunia.com/advisories/31518",
        "http://secunia.com/advisories/31687",
        "http://secunia.com/advisories/33937",
        "http://secunia.com/advisories/38675",
        "http://security.gentoo.org/glsa/glsa-200807-01.xml",
        "http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289",
        "http://support.apple.com/kb/HT3438",
        "http://support.avaya.com/css/P8/documents/100074697",
        "http://wiki.rpath.com/wiki/Advisories:rPSA-2008-0149",
        "http://www.debian.org/security/2008/dsa-1551",
        "http://www.debian.org/security/2008/dsa-1620",
        "http://www.mandriva.com/security/advisories?name=MDVSA-2008:163",
        "http://www.mandriva.com/security/advisories?name=MDVSA-2008:164",
        "http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900",
        "http://www.ubuntu.com/usn/usn-632-1",
        "https://exchange.xforce.ibmcloud.com/vulnerabilities/41958",
        "https://issues.rpath.com/browse/RPL-2424",
        "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A10583",
        "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A7800"
    ],
    "refmap": {
        "apple": [
            "APPLE-SA-2009-02-12"
        ],
        "confirm": [
            "http://bugs.python.org/issue1179",
            "http://support.apple.com/kb/HT3438",
            "http://support.avaya.com/css/P8/documents/100074697",
            "http://wiki.rpath.com/wiki/Advisories:rPSA-2008-0149",
            "http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900",
            "https://issues.rpath.com/browse/RPL-2424"
        ],
        "debian": [
            "DSA-1551",
            "DSA-1620"
        ],
        "gentoo": [
            "GLSA-200807-01"
        ],
        "mandriva": [
            "MDVSA-2008:163",
            "MDVSA-2008:164"
        ],
        "misc": [
            "http://bugs.python.org/msg64682"
        ],
        "secunia": [
            "29889",
            "29955",
            "30872",
            "31255",
            "31358",
            "31365",
            "31518",
            "31687",
            "33937",
            "38675"
        ],
        "slackware": [
            "SSA:2008-217-01"
        ],
        "suse": [
            "SUSE-SR:2008:017"
        ],
        "ubuntu": [
            "USN-632-1"
        ],
        "xf": [
            "python-imageopc-bo(41958)"
        ]
    },
    "statements": [
        {
            "contributor": "Joshua Bressers",
            "lastmodified": "2008-04-22",
            "organization": "Red Hat",
            "statement": "Red Hat is aware of this issue and is tracking it via the following bug: https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=CVE-2008-1679\n\nThe Red Hat Security Response Team has rated this issue as having low security impact, a future update may address this flaw.  More information regarding issue severity can be found here: http://www.redhat.com/security/updates/classification/"
        }
    ],
    "summary": "Multiple integer overflows in imageop.c in Python before 2.5.3 allow context-dependent attackers to cause a denial of service (crash) and possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows.  NOTE: this issue is due to an incomplete fix for CVE-2007-4965.",
    "vulnerable_configuration": [
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.4:*:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python_software_foundation:python:2.4:*:*:*:*:*:*:*"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:*:*:*:*:*:*:*:*",
            "title": "cpe:2.3:a:python_software_foundation:python:*:*:*:*:*:*:*:*"
        }
    ],
    "vulnerable_configuration_cpe_2_2": [],
    "vulnerable_product": [
        "cpe:2.3:a:python_software_foundation:python:2.4:*:*:*:*:*:*:*",
        "cpe:2.3:a:python_software_foundation:python:*:*:*:*:*:*:*:*"
    ]
}