{
    "Modified": "2018-12-23T18:29:00.320000",
    "Published": "2018-12-23T18:29:00.307000",
    "capec": [
        {
            "id": "92",
            "name": "Forced Integer Overflow",
            "prerequisites": "The attacker can manipulate the value of an integer variable utilized by the target host.\nThe target host does not do proper range checking on the variable before utilizing it.\nWhen the integer variable is incremented or decremented to an out of range value, it gets a very different value (e.g. very small or negative number)",
            "related_weakness": [
                "190",
                "128",
                "120",
                "122",
                "196",
                "680",
                "697"
            ],
            "solutions": "Use a language or compiler that performs automatic bounds checking.\nCarefully review the service's implementation before making it available to user. For instance you can use manual or automated code review to uncover vulnerabilities such as integer overflow.\nUse an abstraction library to abstract away risky APIs. Not a complete solution.\nAlways do bound checking before consuming user input data.",
            "summary": "This attack forces an integer variable to go out of range. The integer variable is often used as an offset such as size of memory allocation or similarly. The attacker would typically control the value of such variable and try to get it out of range. For instance the integer in question is incremented past the maximum possible value, it may wrap to become a very small, or negative number, therefore providing a very incorrect value which can lead to unexpected behavior. At worst the attacker can execute arbitrary code."
        }
    ],
    "cvss": "5.0",
    "cwe": "CWE-190",
    "id": "CVE-2018-20406",
    "last-modified": "2019-04-16T02:29:04.347000",
    "nessus": [
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "SUSE_SU-2019-0215-1.NASL",
            "description": "This update for python3 fixes the following issues :\n\nSecurity issue fixed :\n\nCVE-2019-5010: Fixed a denial-of-service vulnerability in the X509 certificate parser (bsc#1122191)\n\nCVE-2018-20406: Fixed a integer overflow via a large LONG_BINPUT (bsc#1120644)\n\nNote that Tenable Network Security has extracted the preceding description block directly from the SUSE security advisory. Tenable has attempted to automatically clean and format it as much as possible without introducing additional issues.",
            "last seen": "2019-02-21",
            "modified": "2019-02-11",
            "plugin id": "121540",
            "published": "2019-02-01",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=121540",
            "title": "SUSE SLED15 / SLES15 Security Update : python3 (SUSE-SU-2019:0215-1)"
        },
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "SUSE_SU-2019-0243-1.NASL",
            "description": "This update for python3 fixes the following issues :\n\nSecurity issue fixed :\n\nCVE-2019-5010: Fixed a denial-of-service vulnerability in the X509 certificate parser (bsc#1122191)\n\nCVE-2018-20406: Fixed a integer overflow via a large LONG_BINPUT (bsc#1120644)\n\nNote that Tenable Network Security has extracted the preceding description block directly from the SUSE security advisory. Tenable has attempted to automatically clean and format it as much as possible without introducing additional issues.",
            "last seen": "2019-02-21",
            "modified": "2019-02-11",
            "plugin id": "121616",
            "published": "2019-02-06",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=121616",
            "title": "SUSE SLED12 / SLES12 Security Update : python3 (SUSE-SU-2019:0243-1)"
        },
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "OPENSUSE-2019-155.NASL",
            "description": "This update for python3 fixes the following issues :\n\nSecurity issue fixed :\n\n  - CVE-2019-5010: Fixed a denial-of-service vulnerability     in the X509 certificate parser (bsc#1122191)\n\n  - CVE-2018-20406: Fixed a integer overflow via a large     LONG_BINPUT (bsc#1120644)\n\nThis update was imported from the SUSE:SLE-15:Update update project.",
            "last seen": "2019-02-21",
            "modified": "2019-02-11",
            "plugin id": "122091",
            "published": "2019-02-11",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=122091",
            "title": "openSUSE Security Update : python3 (openSUSE-2019-155)"
        },
        {
            "NASL family": "Debian Local Security Checks",
            "NASL id": "DEBIAN_DLA-1663.NASL",
            "description": "This DLA fixes a a problem parsing x509 certificates, an pickle integer overflow, and some other minor issues :\n\nCVE-2016-0772\n\nThe smtplib library in CPython does not return an error when StartTLS fails, which might allow man-in-the-middle attackers to bypass the TLS protections by leveraging a network position between the client and the registry to block the StartTLS command, aka a 'StartTLS stripping attack.'\n\nCVE-2016-5636\n\nInteger overflow in the get_data function in zipimport.c in CPython allows remote attackers to have unspecified impact via a negative data size value, which triggers a heap-based buffer overflow.\n\nCVE-2016-5699\n\nCRLF injection vulnerability in the HTTPConnection.putheader function in urllib2 and urllib in CPython allows remote attackers to inject arbitrary HTTP headers via CRLF sequences in a URL.\n\nCVE-2018-20406\n\nModules/_pickle.c has an integer overflow via a large LONG_BINPUT value that is mishandled during a 'resize to twice the size' attempt.\nThis issue might cause memory exhaustion, but is only relevant if the pickle format is used for serializing tens or hundreds of gigabytes of data.\n\nCVE-2019-5010\n\nNULL pointer dereference using a specially crafted X509 certificate.\n\nFor Debian 8 'Jessie', these problems have been fixed in version 3.4.2-1+deb8u2.\n\nWe recommend that you upgrade your python3.4 packages.\n\nNOTE: Tenable Network Security has extracted the preceding description block directly from the DLA security advisory. Tenable has attempted to automatically clean and format it as much as possible without introducing additional issues.",
            "last seen": "2019-02-21",
            "modified": "2019-02-08",
            "plugin id": "122036",
            "published": "2019-02-08",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=122036",
            "title": "Debian DLA-1663-1 : python3.4 security update"
        }
    ],
    "references": [
        "https://bugs.python.org/issue34656",
        "https://github.com/python/cpython/commit/a4ae828ee416a66d8c7bf5ee71d653c2cc6a26dd",
        "https://lists.debian.org/debian-lts-announce/2019/02/msg00011.html",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/46PVWY5LFP4BRPG3BVQ5QEEFYBVEXHCK/",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AEZ5IQT7OF7Q2NCGIVABOWYGKO7YU3NJ/",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/D3LXPABKVLFYUHRYJPM3CSS5MS6FXKS7/",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ICBEGRHIPHWPG2VGYS6R4EVKVUUF4AQW/",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JSKPGPZQNTAULHW4UH63KGOOUIDE4RRB/",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TR6GCO3WTV4D5L23WTCBF275VE6BVNI3/",
        "https://security.netapp.com/advisory/ntap-20190416-0010/"
    ],
    "refmap": {
        "confirm": [
            "https://security.netapp.com/advisory/ntap-20190416-0010/"
        ],
        "fedora": [
            "FEDORA-2019-51f1e08207",
            "FEDORA-2019-6b02154aa0",
            "FEDORA-2019-6baeb15da3",
            "FEDORA-2019-6e1938a3c5",
            "FEDORA-2019-7d9f3cf3ce",
            "FEDORA-2019-cf725dd20b"
        ],
        "misc": [
            "https://bugs.python.org/issue34656",
            "https://github.com/python/cpython/commit/a4ae828ee416a66d8c7bf5ee71d653c2cc6a26dd"
        ],
        "mlist": [
            "[debian-lts-announce] 20190207 [SECURITY] [DLA 1663-1] python3.4 security update"
        ]
    },
    "summary": "Modules/_pickle.c in Python before 3.7.1 has an integer overflow via a large LONG_BINPUT value that is mishandled during a \"resize to twice the size\" attempt. This issue might cause memory exhaustion, but is only relevant if the pickle format is used for serializing tens or hundreds of gigabytes of data.",
    "vulnerable_configuration": [
        {
            "id": "cpe:2.3:o:debian:debian_linux:8.0",
            "title": "Debian Linux 8.0 (Jessie)"
        },
        {
            "id": "cpe:2.3:o:fedoraproject:fedora:28",
            "title": "Fedora 28"
        },
        {
            "id": "cpe:2.3:o:fedoraproject:fedora:29",
            "title": "Fedora 29"
        },
        {
            "id": "cpe:2.3:o:fedoraproject:fedora:30",
            "title": "Fedora 30"
        }
    ],
    "vulnerable_configuration_cpe_2_2": [
        "cpe:/o:debian:debian_linux:8.0",
        "cpe:/o:fedoraproject:fedora:28",
        "cpe:/o:fedoraproject:fedora:29",
        "cpe:/o:fedoraproject:fedora:30"
    ]
}