{
    "Modified": "2014-10-24T03:30:42.527-04:00",
    "Published": "2014-10-08T13:55:05.187-04:00",
    "access": {
        "authentication": "NONE",
        "complexity": "LOW",
        "vector": "NETWORK"
    },
    "capec": [],
    "cvss": "6.4",
    "cvss-time": "2014-10-09T09:53:15.110-04:00",
    "cwe": "CWE-189",
    "id": "CVE-2014-7185",
    "impact": {
        "availability": "PARTIAL",
        "confidentiality": "PARTIAL",
        "integrity": "NONE"
    },
    "last-modified": "2016-10-14T21:59:53.673-04:00",
    "map_cve_bid": {
        "bidid": "70089"
    },
    "map_cve_fedora": {
        "fedoraid": "FEDORA-2014-11559"
    },
    "map_cve_nessus": {
        "nessus_script_family": "SuSE Local Security Checks",
        "nessus_script_file": "suse_11_python-2014-11-19-141119.nasl",
        "nessus_script_id": "79619",
        "nessus_script_name": "SuSE 11.3 Security Update : Python (SAT Patch Number 9996)"
    },
    "map_cve_openvas": {
        "openvas_script_family": "Oracle Linux Local Security Checks",
        "openvas_script_file": "ELSA-2015-1330.nasl",
        "openvas_script_id": "103347",
        "openvas_script_name": "Oracle Linux Local Check: ELSA-2015-1330"
    },
    "map_cve_oval": {
        "cpeid": "",
        "ovalclass": "patch",
        "ovalid": "oval:org.mitre.oval:def:27540",
        "ovaltitle": "SUSE-SU-2014:1511-1 -- Security update for python, python-base, python-doc (moderate)"
    },
    "map_cve_redhat": {
        "redhatid": "RHSA-2015:2101",
        "redhatovalid": "oval:com.redhat.rhsa:def:20152101",
        "redhatupdatedesc": "RHSA-2015:2101: python security, bug fix, and enhancement update (Moderate)"
    },
    "map_cve_scip": {
        "scipid": "71877",
        "sciplink": "http://www.scip.ch/en/?vuldb.71877"
    },
    "map_cve_suse": {
        "suseid": "openSUSE-SU-2014:1292"
    },
    "map_redhat_bugzilla": {
        "advisory_dateissue": "2015-06-25",
        "bugzillaid": "1259421",
        "bugzillatitle": "Backport SSLSocket.version() to python 2.7.5",
        "redhatid": "RHSA-2015:2101"
    },
    "ranking": [
        [
            {
                "circl": 2
            }
        ]
    ],
    "references": [
        "http://bugs.python.org/issue21831",
        "http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html",
        "http://lists.fedoraproject.org/pipermail/package-announce/2014-October/139663.html",
        "http://lists.opensuse.org/opensuse-updates/2014-10/msg00016.html",
        "http://www.openwall.com/lists/oss-security/2014/09/23/5",
        "http://www.openwall.com/lists/oss-security/2014/09/25/47",
        "http://www.oracle.com/technetwork/topics/security/linuxbulletinjan2016-2867209.html",
        "http://www.oracle.com/technetwork/topics/security/linuxbulletinoct2015-2719645.html",
        "http://www.securityfocus.com/bid/70089",
        "http://xforce.iss.net/xforce/xfdb/96193",
        "https://bugzilla.redhat.com/show_bug.cgi?id=1146026",
        "https://support.apple.com/kb/HT205031"
    ],
    "summary": "Integer overflow in bufferobject.c in Python before 2.7.8 allows context-dependent attackers to obtain sensitive information from process memory via a large size and offset in a \"buffer\" function.",
    "vulnerable_configuration": [
        {
            "id": "cpe:2.3:a:python:python:2.7",
            "title": "Python 2.7"
        },
        {
            "id": "cpe:2.3:a:python:python:2.7.1",
            "title": "Python 2.7.1"
        },
        {
            "id": "cpe:2.3:a:python:python:2.7.1:rc1",
            "title": "Python 2.7.1 Release Candiate 1"
        },
        {
            "id": "cpe:2.3:a:python:python:2.7.1150",
            "title": "Python 2.7.1150"
        },
        {
            "id": "cpe:2.3:a:python:python:2.7.1150:-:-:-:-:-:x64",
            "title": "Python 2.7.1150 (x64) 64-bit"
        },
        {
            "id": "cpe:2.3:a:python:python:2.7.2:rc1",
            "title": "Python 2.7.2 Release Candidate 1"
        },
        {
            "id": "cpe:2.3:a:python:python:2.7.2150",
            "title": "Python 2.7.2150"
        },
        {
            "id": "cpe:2.3:a:python:python:2.7.3",
            "title": "Python 2.7.3"
        },
        {
            "id": "cpe:2.3:a:python:python:2.7.4",
            "title": "Python 2.7.4"
        },
        {
            "id": "cpe:2.3:a:python:python:2.7.5",
            "title": "Python 2.7.5"
        },
        {
            "id": "cpe:2.3:a:python:python:2.7.6",
            "title": "Python 2.7.6"
        },
        {
            "id": "cpe:2.3:a:python:python:2.7.7",
            "title": "Python 2.7.7"
        },
        {
            "id": "cpe:2.3:o:apple:mac_os_x:10.10.4",
            "title": "Apple Mac OS X 10.10.4"
        }
    ],
    "vulnerable_configuration_cpe_2_2": [
        "cpe:/a:python:python:2.7",
        "cpe:/a:python:python:2.7.1",
        "cpe:/a:python:python:2.7.1:rc1",
        "cpe:/a:python:python:2.7.1150",
        "cpe:/a:python:python:2.7.1150::~~~~x64~",
        "cpe:/a:python:python:2.7.2:rc1",
        "cpe:/a:python:python:2.7.2150",
        "cpe:/a:python:python:2.7.3",
        "cpe:/a:python:python:2.7.4",
        "cpe:/a:python:python:2.7.5",
        "cpe:/a:python:python:2.7.6",
        "cpe:/a:python:python:2.7.7",
        "cpe:/o:apple:mac_os_x:10.10.4"
    ]
}